src/AppBundle/Entity/Commit.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use SimpSpector\Analyser\Issue;
use SimpSpector\Analyser\Metric;
use Symfony\Component\Serializer\Annotation as JSON;

/**
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CommitRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Commit implements TimestampableInterface
{
    use Timestampable;

    const STATUS_NEW     = 'new';
    const STATUS_RUN     = 'run';
    const STATUS_SUCCESS = 'success';
    const STATUS_ERROR   = 'error';

    /**
     * @var integer
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @JSON\Groups({"commit_full"})
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $revision;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $gitRepository;

    /**
     * @var MergeRequest[]
     *
     * @ORM\ManyToMany(targetEntity="MergeRequest", inversedBy="commits", cascade={"all"})
     */
    private $mergeRequests;

    /**
     * @var Branch[]
     *
     * @ORM\ManyToMany(targetEntity="Branch", inversedBy="commits", cascade={"all"})
     */
    private $branches;


    /**
     * @var Tag[]
     *
     * @ORM\OneToMany(targetEntity="Tag", mappedBy="commit", cascade={"all"})
     */
    private $tags;

    /**
     * @var Project
     *
     * @ORM\ManyToOne(targetEntity="Project", inversedBy="commits", cascade={"all"})
     */
    private $project;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $status;

    /**
     * @var Result
     *
     * @ORM\Embedded(class="AppBundle\Entity\Result", columnPrefix="result_")
     *
     * @JSON\Groups({"commit_full"})
     */
    private $result;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $commitMessage;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $authorName;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $authorEmail;

    /**
     *
     */
    public function __construct()
    {
        $this->mergeRequests = new ArrayCollection();
        $this->branches      = new ArrayCollection();
        $this->status        = self::STATUS_NEW;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set revision
     *
     * @param string $revision
     */
    public function setRevision($revision)
    {
        $this->revision = $revision;
    }

    /**
     * Get revision
     *
     * @return string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * @return string
     */
    public function getGitRepository()
    {
        return $this->gitRepository;
    }

    /**
     * @param string $gitRepository
     */
    public function setGitRepository($gitRepository)
    {
        $this->gitRepository = $gitRepository;
    }

    /**
     * @return MergeRequest[]|ArrayCollection
     */
    public function getMergeRequests()
    {
        return $this->mergeRequests;
    }

    /**
     * @return Tag[]|ArrayCollection
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @return Branch[]|ArrayCollection
     */
    public function getBranches()
    {
        return $this->branches;
    }

    /**
     * @return Project
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * @param Project $project
     */
    public function setProject(Project $project)
    {
        $this->project = $project;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param string $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @param Result $result
     */
    public function setResult(Result $result = null)
    {
        $this->result = $result;
    }

    /**
     * @return Result
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * @return Issue[]
     */
    public function getIssues()
    {
        return $this->result->getIssues();
    }

    /**
     * @return Metric[]
     */
    public function getMetrics()
    {
        return $this->result->getMetrics();
    }

    /**
     * @param string $code
     * @return Metric|null
     */
    public function getMetric($code)
    {
        return $this->result->getMetric($code);
    }

    /**
     * @param string $code
     * @return bool
     */
    public function hasMetric($code)
    {
        return $this->result->hasMetric($code);
    }

    /**
     * @return string
     */
    public function getCommitMessage()
    {
        return $this->commitMessage;
    }

    /**
     * @param string $commitMessage
     */
    public function setCommitMessage($commitMessage)
    {
        $this->commitMessage = $commitMessage;
    }

    /**
     * @return string
     */
    public function getAuthorName()
    {
        return $this->authorName;
    }

    /**
     * @param string $authorName
     */
    public function setAuthorName($authorName)
    {
        $this->authorName = $authorName;
    }

    /**
     * @return string
     */
    public function getAuthorEmail()
    {
        return $this->authorEmail;
    }

    /**
     * @param string $authorEmail
     */
    public function setAuthorEmail($authorEmail)
    {
        $this->authorEmail = $authorEmail;
    }

    /**
     * @return string
     */
    public function getUniqueId()
    {
        return sprintf(
            "%s_%s",
            $this->getProject()->getId(),
            $this->getRevision()
        );
    }
}

src/AppBundle/Entity/Project.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ProjectRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Project implements TimestampableInterface
{
    use Timestampable;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $namespace;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $repositoryUrl;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $webUrl;

    /**
     * @var string
     *
     * @ORM\Column(name="remoteId", type="string", length=255)
     */
    private $remoteId;

    /**
     * @var MergeRequest[]
     *
     * @ORM\OneToMany(targetEntity="MergeRequest", mappedBy="project")
     */
    private $mergeRequests;

    /**
     * @var Branch[]
     *
     * @ORM\OneToMany(targetEntity="Branch", mappedBy="project")
     */
    private $branches;

    /**
     * @var Tag[]
     *
     * @ORM\OneToMany(targetEntity="Tag", mappedBy="project")
     */
    private $tags;

    /**
     * @var Commit[]
     *
     * @ORM\OneToMany(targetEntity="Commit", mappedBy="project")
     */
    private $commits;

    /**
     * @var NewsStreamItem[]
     *
     * @ORM\OneToMany(targetEntity="NewsStreamItem", mappedBy="project")
     */
    private $newsStreamItems;

    /**
     *
     */
    public function __construct()
    {
        $this->mergeRequests   = new ArrayCollection();
        $this->branches        = new ArrayCollection();
        $this->commits         = new ArrayCollection();
        $this->tags            = new ArrayCollection();
        $this->newsStreamItems = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * @param string $namespace
     */
    public function setNamespace($namespace)
    {
        $this->namespace = $namespace;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getRepositoryUrl()
    {
        return $this->repositoryUrl;
    }

    /**
     * @param string $repository
     */
    public function setRepositoryUrl($repository)
    {
        $this->repositoryUrl = $repository;
    }

    /**
     * @return string
     */
    public function getWebUrl()
    {
        return $this->webUrl;
    }

    /**
     * @param string $webUrl
     */
    public function setWebUrl($webUrl)
    {
        $this->webUrl = $webUrl;
    }

    /**
     * Set remoteId
     *
     * @param string $remoteId
     * @return Project
     */
    public function setRemoteId($remoteId)
    {
        $this->remoteId = $remoteId;

        return $this;
    }

    /**
     * Get remoteId
     *
     * @return string
     */
    public function getRemoteId()
    {
        return $this->remoteId;
    }

    /**
     * @return MergeRequest[]|ArrayCollection
     */
    public function getMergeRequests()
    {
        return $this->mergeRequests;
    }

    /**
     * @return Branch[]|ArrayCollection
     */
    public function getBranches()
    {
        return $this->branches;
    }

    /**
     * @return Tag[]|ArrayCollection
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @return Commit[]|ArrayCollection
     */
    public function getCommits()
    {
        return $this->commits;
    }

    /**
     * @return NewsStreamItem[]|ArrayCollection
     */
    public function getNewsStreamItems()
    {
        return $this->newsStreamItems;
    }

    /**
     * @return string
     */
    public function getFullName()
    {
        /* todo remove */
        if (!$this->namespace) {
            return $this->name;
        }

        return $this->namespace . '/' . $this->name;
    }
}

src/AppBundle/Controller/ProjectController.php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration as Framework;
use AppBundle\Entity\Project;
use AppBundle\Repository\CommitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * @Framework\Route("/projects")
 *
 * @author Tobias Olry <tobias.olry@gmail.com>
 */
class ProjectController extends Controller
{
    /**
     * @Framework\Route("/", name="project_list")
     * @Framework\Template()
     *
     * @return array
     */
    public function listAction()
    {
        return ['projects' => $this->get('simpspector.app.repository.project')->findAll()];
    }

    /**
     * @Framework\Route("/{id}/show", name="project_show")
     * @Framework\Template()
     *
     * @param Project $project
     *
     * @return array
     */
    public function showAction(Project $project)
    {
        $mergeRequestRepository = $this->get('simpspector.app.repository.merge_request');
        $commitRepository = $this->get('simpspector.app.repository.commit');
        $newsStreamItemRepository = $this->get('simpspector.app.repository.news_stream_item');


        $mergeRequests = $mergeRequestRepository->findBy(['project' => $project], [
            'status' => 'DESC',
            'id' => 'DESC'
        ]);

        $projectCommits = $commitRepository->findCommitsByProject($project);

        $newsStreamItems = $newsStreamItemRepository->findByProject($project);

        return [
            'project' => $project,
            'merge_requests' => $mergeRequests,
            'project_commits' => $projectCommits,
            'news_stream_items' => $newsStreamItems
        ];
    }

    /**
     * @Framework\Route("/{id}/last-commit", name="project_lastcommit")
     *
     * @param Project $project
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function lastCommitAction(Project $project)
    {
        /** @var CommitRepository */
        $repository = $this->get('simpspector.app.repository.commit');
        $commit = $repository->findLastInMaster($project);

        if (!$commit) {
            throw new NotFoundHttpException();
        }

        return $this->redirect($this->generateUrl('commit_show', ['id' => $commit->getId()]));
    }
}

src/AppBundle/Resources/views/Project/list.html.twig
{% extends 'AppBundle::layout.html.twig' %}
{% import 'AppBundle::macros.html.twig' as _ %}

{% block content %}
    <div class="row">
        <div class="column wide sixteen">
            <div class="ui steps">
                <div class="content">
                    <a href="{{ url('homepage') }}"><div class="logo logo-breadcrumb"></div></a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="column wide sixteen">
            <div class="ui segment">

                <div class="ui secondary pointing menu">
                    <a class="item" href="{{ path('homepage') }}">
                        <i class="rss icon"></i> Newsstream
                    </a>
                    <a class="item active" href="{{ path('project_list') }}">
                        <i class="cubes icon"></i> Projects
                    </a>
                </div>

                <table class="ui table">
                    <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>Name</th>
                        <th>Issues</th>
                        <th>Score</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for project in projects %}
                        <tr>
                            <td>
                                <a class="ui animated button" href="{{ path('project_show', {id: project.id}) }}">
                                    <div class="hidden content">show</div>
                                    <div class="visible content">
                                        <i class="search icon"></i>
                                    </div>
                                </a>
                            </td>
                            <td>{{ project.fullName }}</td>
                            <td>{{ _.levels((project.commits|last).issues) }}</td>
                            <td>-</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Project/master.html.twig
{% extends 'AppBundle::layout.html.twig' %}
{% import 'AppBundle::macros.html.twig' as _ %}

{% block content %}
    <div class="row">
        <div class="column wide sixteen">
            <div class="ui steps">
                <div class="content">
                    <a href="{{ url('homepage') }}"><div class="logo logo-breadcrumb"></div></a>
                </div>
                {{ _.step(project.fullName, 'Project', 'icon cubes', path('project_show', {id: project.id })) }}
                {{ _.step('Master Branch', 'Branch', 'sitemap alternate icon', '') }}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="column wide sixteen">
            <div class="ui segment">
                <h3 class="ui header">
                    <i class="icon text file inverted circular"></i> Commits
                </h3>
                {% include 'AppBundle::commits.html.twig' %}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="column wide sixteen">
            <div class="ui segment">
                <h3 class="ui header">
                    <i class="icon text code inverted circular"></i> Badge
                </h3>

                <div class="ui tertiary inverted segment">
                    <div class="ui top right attached label">Markdown</div>
                    <p>{{ markdown }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Project/mergeRequests.html.twig
<table class="ui table">

    <thead>
    <tr>
        <th></th>
        <th>Name</th>
        <th>Issues</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
    {% for merge_request in merge_requests %}
        <tr>
            <td>
                <a class="ui animated button" href="{{ path('mergerequest_show', {id: merge_request.id}) }}">
                    <div class="hidden content">show</div>
                    <div class="visible content">
                        <i class="search icon"></i>
                    </div>
                </a>
            </td>
            <td>{{ merge_request.name }}</td>
            <td>{{ _.levels(merge_request.commits|first) }}</td>
            <td>
                {% if merge_request.status == constant('STATUS_OPENED', merge_request) %}
                    <span class="ui green label">Open</span>
                {% elseif merge_request.status == constant('STATUS_MERGED', merge_request) %}
                    <span class="ui purple label">Merged</span>
                {% else %}
                    <span class="ui red label">Closed</span>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

src/AppBundle/Resources/views/Project/show.html.twig
{% extends 'AppBundle::layout.html.twig' %}
{% import 'AppBundle::macros.html.twig' as _ %}

{% block content %}
    <div class="row">
        <div class="column wide sixteen">
            <div class="ui steps">
                <div class="content">
                    <a href="{{ url('homepage') }}">
                        <div class="logo logo-breadcrumb"></div>
                    </a>
                </div>
                {{ _.step(project.fullName, 'Project', 'icon cubes', '') }}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="eleven wide column">
            <div class="ui segment">

                <div class="ui secondary pointing menu">
                    <a class="item active" data-tab="newsstream">
                        <i class="rss icon"></i> Newsstream
                    </a>
                    <a class="item" data-tab="mergerequest">
                        <i class="horizontally flipped alternate share icon"></i> Merge Request
                    </a>
                    <a class="item" data-tab="branches">
                        <i class="fork icon"></i> Branches
                    </a>
                    <a class="item" data-tab="tags">
                        <i class="tag icon"></i> Tags
                    </a>

                </div>

                <div class="ui tab active" data-tab="newsstream">
                    {% include 'AppBundle::feed.html.twig' with {items: news_stream_items} %}
                </div>

                <div class="ui tab" data-tab="mergerequest">
                    {% include 'AppBundle:Project:mergeRequests.html.twig' with {merge_requests: merge_requests} %}
                </div>

                <div class="ui tab" data-tab="branches">
                    {% include 'AppBundle:Project:showBranches.html.twig' with {merge_requests: merge_requests} %}
                </div>

                <div class="ui tab" data-tab="tags">
                    {% include 'AppBundle:Project:showTags.html.twig' with {merge_requests: merge_requests} %}
                </div>

            </div>
        </div>
        <div class="five wide column">

            <div class="ui header attached top small">
                <i class="icon alternate cubes"></i>
                {{ project.fullName }}
            </div>

            <div class="ui segment attached">
                <a href="{{ project.repositoryUrl }}" target="_blank">
                    <i class="sitemap icon"></i>
                    {{ project.repositoryUrl }}
                </a>
            </div>

            {% if project.webUrl %}
                <div class="ui segment attached">
                    <a href="{{ project.webUrl }}" target="_blank">
                        <i class="sitemap icon"></i>
                        {{ project.webUrl }}
                    </a>
                </div>
            {% endif %}

            <div class="ui header attached top small">
                <i class="icon text file"></i>
                Last 10 commits
            </div>

            {% for commit in project_commits|slice(0,10) %}
                <div class="ui segment attached">
                    <a href="{{ path('commit_show', {id: commit.id}) }}">{{ commit.revision|slice(0,8) }}</a>
                    <div class="ellipsis">{{ commit.commitMessage }}</div>
                    by {{ commit.authorName|default("unknown") }}
                    {% if commit.authorEmail %}&lt;{{ commit.authorEmail }}&gt;{% endif %}
                    <div style="float: right">{{ _.commit_status_button(commit) }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Project/showBranches.html.twig
<table class="ui table">

    <thead>
    <tr>
        <th></th>
        <th>Name</th>
        <th>Issues</th>
    </tr>
    </thead>
    <tbody>
    {% for branch in project.branches %}
        <tr>
            <td>
                <a class="ui animated button" href="{{ path('branch_show', {id: branch.id}) }}">
                    <div class="hidden content">show</div>
                    <div class="visible content">
                        <i class="search icon"></i>
                    </div>
                </a>
            </td>
            <td>{{ branch.name }}</td>
            <td>{{ _.levels(branch.commits|first) }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

src/AppBundle/Resources/views/Project/showTags.html.twig
<table class="ui table">

    <thead>
    <tr>
        <th></th>
        <th>Name</th>
        <th>Issues</th>
    </tr>
    </thead>
    <tbody>
    {% for tag in project.tags %}
        <tr>
            <td>
                <a class="ui animated button" href="{{ path('commit_show', {id: tag.commit.id}) }}">
                    <div class="hidden content">show</div>
                    <div class="visible content">
                        <i class="search icon"></i>
                    </div>
                </a>
            </td>
            <td>{{ tag.name }}</td>
            <td>{{ _.levels(tag.commit) }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>