src/AppBundle/Entity/Project.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ProjectRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Project implements TimestampableInterface
{
    use Timestampable;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $namespace;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $repositoryUrl;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $webUrl;

    /**
     * @var string
     *
     * @ORM\Column(name="remoteId", type="string", length=255)
     */
    private $remoteId;

    /**
     * @var MergeRequest[]
     *
     * @ORM\OneToMany(targetEntity="MergeRequest", mappedBy="project")
     */
    private $mergeRequests;

    /**
     * @var Branch[]
     *
     * @ORM\OneToMany(targetEntity="Branch", mappedBy="project")
     */
    private $branches;

    /**
     * @var Tag[]
     *
     * @ORM\OneToMany(targetEntity="Tag", mappedBy="project")
     */
    private $tags;

    /**
     * @var Commit[]
     *
     * @ORM\OneToMany(targetEntity="Commit", mappedBy="project")
     */
    private $commits;

    /**
     * @var NewsStreamItem[]
     *
     * @ORM\OneToMany(targetEntity="NewsStreamItem", mappedBy="project")
     */
    private $newsStreamItems;

    /**
     *
     */
    public function __construct()
    {
        $this->mergeRequests   = new ArrayCollection();
        $this->branches        = new ArrayCollection();
        $this->commits         = new ArrayCollection();
        $this->tags            = new ArrayCollection();
        $this->newsStreamItems = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * @param string $namespace
     */
    public function setNamespace($namespace)
    {
        $this->namespace = $namespace;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getRepositoryUrl()
    {
        return $this->repositoryUrl;
    }

    /**
     * @param string $repository
     */
    public function setRepositoryUrl($repository)
    {
        $this->repositoryUrl = $repository;
    }

    /**
     * @return string
     */
    public function getWebUrl()
    {
        return $this->webUrl;
    }

    /**
     * @param string $webUrl
     */
    public function setWebUrl($webUrl)
    {
        $this->webUrl = $webUrl;
    }

    /**
     * Set remoteId
     *
     * @param string $remoteId
     * @return Project
     */
    public function setRemoteId($remoteId)
    {
        $this->remoteId = $remoteId;

        return $this;
    }

    /**
     * Get remoteId
     *
     * @return string
     */
    public function getRemoteId()
    {
        return $this->remoteId;
    }

    /**
     * @return MergeRequest[]|ArrayCollection
     */
    public function getMergeRequests()
    {
        return $this->mergeRequests;
    }

    /**
     * @return Branch[]|ArrayCollection
     */
    public function getBranches()
    {
        return $this->branches;
    }

    /**
     * @return Tag[]|ArrayCollection
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @return Commit[]|ArrayCollection
     */
    public function getCommits()
    {
        return $this->commits;
    }

    /**
     * @return NewsStreamItem[]|ArrayCollection
     */
    public function getNewsStreamItems()
    {
        return $this->newsStreamItems;
    }

    /**
     * @return string
     */
    public function getFullName()
    {
        /* todo remove */
        if (!$this->namespace) {
            return $this->name;
        }

        return $this->namespace . '/' . $this->name;
    }
}

src/AppBundle/Entity/TimestampableInterface.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @author David Badura <d.a.badura@gmail.com>
 *
 */
interface TimestampableInterface
{
    /**
     * @return \DateTime
     */
    public function getCreatedAt();

    /**
     * @return \DateTime
     */
    public function getUpdatedAt();
}

src/AppBundle/Resources/views/commits.html.twig
{% import 'AppBundle::macros.html.twig' as _ %}

<table class="ui table">
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>revision</th>
        <th>issues</th>
        <th>status</th>
    </tr>
    </thead>
    <tbody>
    {% for commit in commits %}
        <tr>
            <td>
                <a class="ui animated button" href="{{ path('commit_show', {id: commit.id}) }}">
                    <div class="hidden content">show</div>
                    <div class="visible content">
                        <i class="search icon"></i>
                    </div>
                </a>
            </td>
            <td>{{ commit.revision }}</td>
            <td>{{ _.levels(commit) }}</td>
            <td>
                {% if commit.status == constant('STATUS_NEW', commit) %}
                    <span class="ui label">New</span>
                {% elseif commit.status == constant('STATUS_RUN', commit) %}
                    <span class="ui yellow label">Proccess</span>
                {% elseif commit.status == constant('STATUS_SUCCESS', commit) %}
                    <span class="ui green label">Success</span>
                {% else %}
                    <span class="ui red label">Error</span>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

src/AppBundle/Resources/views/feed.html.twig
{% import 'AppBundle::macros.html.twig' as _ %}

{% set last_project = '' %}
{% for item in items %}
    {% set commit = item.commit %}
    {% if last_project != item.project.fullName %}
    {% set last_project = item.project.fullName %}
    <div class="ui ribbon label">
        <a href="{{ path('project_show', {id: item.project.id}) }}">{{ item.project.fullName }}</a>
    </div>
    {% endif %}
    <div class="ui segment">
        <p class="ui right floated column">
            <i class="clock icon"></i> {{ item.createdAt|date('H:i Y-m-d') }}
        </p>
        <p>
            {{ _.commit_status_button(commit) }}
            {% if item.type == 'branch' %}
                <i class="fork icon"></i>
                <a href="{{ path('branch_show', {id: item.branch.id }) }}" title="branch">
                    {{ item.branch.name }}
                </a>
            {% elseif item.type == 'tag' %}
                <i class="tag icon"></i>
                <a href="{{ path('commit_show', {id: commit.id}) }}" title="tag ">
                    {{ item.tag.name }}
                </a>
            {% elseif item.type == 'merge_request' %}
                <i class="horizontally flipped alternate share icon"></i>
                <a href="{{ path('mergerequest_show', {id: item.mergeRequest.id }) }}" title="merge request">
                    {{ item.mergeRequest.name }}
                </a>
            {% endif %}
            <i class="github icon"></i>
            <a href="{{ path('commit_show', {id: commit.id}) }}">
                #{{ commit.revision|slice(0, 8) }}
            </a>
        </p>
        <div class="ellipsis"><i>{{ commit.commitMessage }}</i></div>
        <div class="ui right floated column" style="clear:right;">
            {% if commit.issues|length > 0 %}
            {{ _.levels(commit) }}
            {% endif %}
        </div>
        <p>
            <img class="commit-gravatar" src="{{ gravatar(commit.authorEmail, 16) }}"
                 alt="{{ commit.authorName }}">
            {{ commit.authorName }}
        </p>
    </div>
{% endfor %}

src/AppBundle/Resources/views/layout.html.twig
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="UTF-8">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
    <link rel="stylesheet" href="{{ asset('build/style.css') }}" />

</head>
<body data-base="{{ path('homepage') }}">
    <main class="ui page grid">
        {% block content %}{% endblock %}
    </main>

    <script type="text/javascript" src="{{ asset('build/app.js') }}"></script>
</body>
</html>

src/AppBundle/Resources/views/macros.html.twig
{% macro levels(commit) %}

    {% if commit.getMetric('count.notice').value|default(0) %}
        <span class="ui" title="notice">
                <i class="info icon blue "></i>
            {{ commit.getMetric('count.notice').value }}
            </span>
    {% endif %}

    {% if commit.getMetric('count.warning').value|default(0) %}
        <span class="ui" title="warning">
                <i class="warning icon yellow "></i>
            {{ commit.getMetric('count.warning').value }}
            </span>
    {% endif %}

    {% if commit.getMetric('count.error').value|default(0) %}
        <span class="ui" title="error">
                <i class="bug icon orange "></i>
            {{ commit.getMetric('count.error').value }}
            </span>
    {% endif %}

    {% if commit.getMetric('count.critical').value|default(0) %}
        <span class="ui" title="critical">
                <i class="fire icon red "></i>
            {{ commit.getMetric('count.critical').value }}
            </span>
    {% endif %}

{% endmacro %}

{% macro levels_by_issues(issues) %}

    {% set groups = group_issues(issues) %}

    {% if groups.level is defined %}
        {% for level,issues in groups.level %}
            <span class="ui" title="{{ level }}">
                <i class="{{ issues|first|level_color }} {{ issues|first|level_icon }} icon"></i>
                {{ issues|length }}
            </span>
        {% endfor %}
    {% endif %}
{% endmacro %}

{% macro gadgets(issues) %}
    {% set groups = group_issues(issues) %}

    {% if groups.gadget is defined %}
        {% for gadget in groups.gadget|keys %}
            <span class="ui label">{{ gadget }}</span>
        {% endfor %}
    {% endif %}
{% endmacro %}

{% macro step(title, description, icon, url) %}
    <a class="step tooltip{{ url == '' ? ' active' : '' }}" href="{{ url }}" title="{{ title }}">
        <div class="content">
            <div class="title ellipsis"><i class="{{ icon }}"></i> {{ title|raw }}</div>
            <div class="description ellipsis">{{ description|raw }}</div>
        </div>
    </a>
{% endmacro %}

{% macro commit_status_button(commit) %}
    {% set url = path('commit_show', {id: commit.id}) %}
    {% if commit.status == constant('STATUS_NEW', commit) %}
        <a class="ui label right" href="{{ url }}">New</a>
    {% elseif commit.status == constant('STATUS_RUN', commit) %}
        <a class="ui yellow label right" href="{{ url }}">Running...</a>
    {% elseif commit.status == constant('STATUS_SUCCESS', commit) %}
        <a class="ui green label right" href="{{ url }}">Success</a>
    {% else %}
        <a class="ui red label right" href="{{ url }}">Error</a>
    {% endif %}
{% endmacro %}